[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#0077B6"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F9FC"
textColor = "#1A2B3C"
font = "sans serif"
